GROQ_API_KEY = "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"

[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "movies"
username = "postgres"
password = "postgres"